name: Builder

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builder
    outputs:
      architectures: ${{ steps.init.outputs.architectures }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize HA addon builder info
        id: init
        uses: home-assistant/actions/helpers/addon-info@master

  build:
    needs: init
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Add-on
        uses: home-assistant/builder-action@2024.08.1
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data \
            --image "ghcr.io/${{ github.repository_owner }}/lavalink-app-homeassistant/{arch}" \
            --docker-hub ghcr.io/${{ github.repository_owner }}
